# REF: https://bitwarden.com/help/install-on-premise-linux/

---
- name: Install and configure Bitwarden
  hosts: all
  become: true
  vars:
    app_domain:
    letsencrypt_contact_email:
    service_user_name: bitwarden
    app_directory: /opt/bitwarden
    bw_coreversion: latest
    bw_webversion: latest
    bw_keyconnectorversion: latest
    bw_dbname: vault
    bw_installid:
    bw_installkey:
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Install required system packages
      apt:
        pkg:
          - acl
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    - name: Add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install docker and docker-compose python module
      pip:
        name:
          - docker
          - docker-compose
    - name: Prepare dedicated service user
      register: service_user
      user:
        name: "{{ service_user_name }}"
        password: "!"
        groups: docker
        state: present
        shell: /bin/bash
        update_password: on_create
    - name: Prepare bwdata directory
      file:
        path: "{{ item.path }}"
        state: directory
        mode: 0700
        owner: "{{ service_user_name }}"
        group: "{{ service_user_name }}"
        recurse: yes
      loop:
        - { path: "{{ app_directory }}/bwdata" }
        - { path: "{{ app_directory }}/bwdata/env" }
        - { path: "{{ app_directory }}/bwdata/letsencrypt" }
    - name: Prepare uid.env file
      copy:
        dest: "{{ app_directory }}/bwdata/env/uid.env"
        owner: "{{ service_user_name }}"
        group: "{{ service_user_name }}"
        content: |
          LOCAL_UID={{ service_user.uid }}
          LOCAL_GID={{ service_user.group }}
    - name: Get a fresh Let's Encrypt SSL certificate
      become: true
      become_user: "{{ service_user_name }}"
      args:
        chdir: "{{ app_directory }}"
      command: |
        docker run -it --rm --name certbot \
            -p 80:80 \
            -v {{ app_directory }}/bwdata/letsencrypt:/etc/letsencrypt/ \
          certbot/certbot \
            certonly --standalone --noninteractive --agree-tos \
              --preferred-challenges http \
              --email {{ letsencrypt_contact_email }} \
              -d {{ app_domain }} \
              --logs-dir /etc/letsencrypt/logs
    - name: Setup bitwarden
      become: true
      become_user: "{{ service_user_name }}"
      args:
        chdir: "{{ app_directory }}"
        creates: "{{ app_directory }}/bwdata/docker"
      command: |
        docker run -it --rm --name setup \
            -v {{ app_directory }}/bwdata:/bitwarden \
            --env-file {{ app_directory }}/bwdata/env/uid.env \
          bitwarden/setup:{{ bw_coreversion }} \
            dotnet Setup.dll -install 1 \
              -domain {{ app_domain }} \
              -letsencrypt y \
              -os lin \
              -corev {{ bw_coreversion }} \
              -webv {{ bw_webversion }} \
              -dbname "{{ bw_dbname }}" \
              -keyconnectorv {{ bw_keyconnectorversion }} \
              -install-id {{ bw_installid }} \
              -install-key {{ bw_installkey }}
    - name: Prepare docker-compose volume directories
      file:
        path: "{{ item.path }}"
        state: directory
        mode: 0700
        owner: "{{ service_user_name }}"
        group: "{{ service_user_name }}"
        recurse: yes
      loop:
        - { path: "{{ app_directory }}/core" }
        - { path: "{{ app_directory }}/core/attachments" }
        - { path: "{{ app_directory }}/logs" }
        - { path: "{{ app_directory }}/logs/admin" }
        - { path: "{{ app_directory }}/logs/api" }
        - { path: "{{ app_directory }}/logs/events" }
        - { path: "{{ app_directory }}/logs/icons" }
        - { path: "{{ app_directory }}/logs/identity" }
        - { path: "{{ app_directory }}/logs/mssql" }
        - { path: "{{ app_directory }}/logs/nginx" }
        - { path: "{{ app_directory }}/logs/notifications" }
        - { path: "{{ app_directory }}/logs/sso" }
        - { path: "{{ app_directory }}/logs/portal" }
        - { path: "{{ app_directory }}/mssql/backups" }
        - { path: "{{ app_directory }}/mssql/data" }
    - name: Start docker-compose
      become: true
      become_user: "{{ service_user_name }}"
      community.docker.docker_compose:
        project_src: "{{ app_directory }}/bwdata/docker"
        restarted: true
